"""Tests for the prompt fragment and context pack loader in lassi.prompts (task P1.3).

Bible: Design Principle 3 (prompts and context packs are versioned files
under `assets/`), Repository Layout (`assets/prompts`, `assets/context`),
Readability Standards (Prompts row). OQ-018 is binding: the upstream text is
generated by tools/extract_lassi_assets.py and only manifests are committed.

The contract these tests fix:

- `lassi.prompts.load_recipe_assets(recipe, root=None)` takes a resolved
  recipe mapping and an assets root (default: the repository's `assets/`)
  and returns an object with `fragments`, a mapping {key: text} of every
  entry of the prompt set the recipe's `prompts` names
  (`<root>/prompts/<set>/`), and `packs`, a mapping {name: text} of the
  packs the recipe's `context` names (`<root>/context/<name>/`), and only
  those. A pack of one entry maps to that entry's text.
- Every file is checked against its tree's MANIFEST.yaml (fields in
  conftest.py, Manifests.entries). A missing file or a sha256 mismatch
  raises ValueError naming tools/extract_lassi_assets.py, the tool that
  regenerates it. A pack the recipe names that has no tree raises ValueError
  naming the pack.

Most tests build synthetic trees in a temporary directory: plain ASCII text
written here, not upstream text. The last test loads a fresh extraction of
the pinned upstream checkout and compares every fragment byte for byte with
the upstream value its key names, parsed from the checkout (conftest.py,
Upstream.value_of; skipped, naming the extractor, when the checkout is
absent). No value here is a measurement.
"""

from __future__ import annotations

import hashlib
import shutil
from pathlib import Path
from typing import Any, Callable

import pytest
import yaml

REPO = Path(__file__).resolve().parents[2]
TOOL_NAME = "extract_lassi_assets"
DICTIONARY_FILE = "prompt_dictionary.py"
NOTEBOOK_FILE = "LASSI_pipeline_v0.ipynb"
MANIFEST = "MANIFEST.yaml"
PROMPT_SET = "lassi-2024"
PACKS = {
    "openmp-4.0-card": ("codeknowledge_dict", "omp"),
    "cuda-12.5-ch5": ("codeknowledge_dict", "cuda"),
}

# Synthetic trees: a prompt set and two packs, with text written for these tests.
FIXTURE_SET = "fixture-set"
FIXTURE_FRAGMENTS = {
    "intro": "Synthetic intro fragment.\n  Indented second line.\n",
    "joiner": " and then ",
    "outro": "\nSynthetic outro with a trailing space ",
}
FIXTURE_PACKS = {
    "fixture-pack-a": "Synthetic pack A: one line of reference text.\n",
    "fixture-pack-b": "Synthetic pack B\n\nwith a blank line and no final newline",
}


def loader() -> Callable[..., Any]:
    """Return lassi.prompts.load_recipe_assets, failing clearly while it does not exist."""
    import lassi.prompts as prompts

    load = getattr(prompts, "load_recipe_assets", None)
    assert callable(load), "lassi.prompts.load_recipe_assets is missing (task P1.3 writes it)"
    return load


def write_tree(tree: Path, texts: dict[str, str], *, notebook_key: str | None = None) -> None:
    """Write one `<key>.txt` per text and a MANIFEST.yaml listing them with their sha256.

    The entry named `notebook_key`, if any, cites a notebook cell; the others cite the dictionary.
    """
    tree.mkdir(parents=True)
    entries = []
    for key, text in texts.items():
        data = text.encode("ascii")
        (tree / f"{key}.txt").write_bytes(data)
        entry: dict[str, Any] = {"key": key, "source": DICTIONARY_FILE}
        if key == notebook_key:
            entry = {"key": key, "source": NOTEBOOK_FILE, "cell": "fixture-cell-0001"}
        entry["sha256"] = hashlib.sha256(data).hexdigest()
        entries.append(entry)
    (tree / MANIFEST).write_bytes(yaml.safe_dump({"entries": entries}, sort_keys=False).encode("ascii"))


def fixture_root(tmp_path: Path) -> Path:
    """Build a synthetic assets root holding the fixture prompt set and both fixture packs."""
    root = tmp_path / "assets"
    write_tree(root / "prompts" / FIXTURE_SET, FIXTURE_FRAGMENTS, notebook_key="joiner")
    for name, text in FIXTURE_PACKS.items():
        write_tree(root / "context" / name, {"pack": text})
    return root


def fixture_recipe(*packs: str) -> dict[str, Any]:
    """Return a recipe mapping that names the fixture prompt set and `packs`."""
    return {"prompts": FIXTURE_SET, "context": list(packs)}


def test_loader_returns_the_fragments_and_packs_the_recipe_names(tmp_path: Path) -> None:
    load = loader()
    root = fixture_root(tmp_path)
    assets = load(fixture_recipe("fixture-pack-b"), root=root)
    assert dict(assets.fragments) == FIXTURE_FRAGMENTS
    assert dict(assets.packs) == {"fixture-pack-b": FIXTURE_PACKS["fixture-pack-b"]}
    both = load(fixture_recipe("fixture-pack-a", "fixture-pack-b"), root=root)
    assert dict(both.packs) == FIXTURE_PACKS


@pytest.mark.parametrize("victim", ["prompts/fixture-set/intro.txt", "context/fixture-pack-a/pack.txt"])
def test_loader_names_the_tool_when_a_file_is_missing(victim: str, tmp_path: Path) -> None:
    load = loader()
    root = fixture_root(tmp_path)
    (root / victim).unlink()
    with pytest.raises(ValueError) as caught:
        load(fixture_recipe("fixture-pack-a", "fixture-pack-b"), root=root)
    assert TOOL_NAME in str(caught.value), f"the error does not name the tool: {caught.value}"


@pytest.mark.parametrize("victim", ["prompts/fixture-set/outro.txt", "context/fixture-pack-b/pack.txt"])
def test_loader_names_the_tool_when_a_sha256_differs(victim: str, tmp_path: Path) -> None:
    load = loader()
    root = fixture_root(tmp_path)
    path = root / victim
    path.write_bytes(path.read_bytes() + b"edited")
    with pytest.raises(ValueError) as caught:
        load(fixture_recipe("fixture-pack-a", "fixture-pack-b"), root=root)
    assert TOOL_NAME in str(caught.value), f"the error does not name the tool: {caught.value}"


def test_loader_fails_loudly_on_an_unknown_pack(tmp_path: Path) -> None:
    load = loader()
    root = fixture_root(tmp_path)
    with pytest.raises(ValueError, match="no-such-pack"):
        load(fixture_recipe("fixture-pack-a", "no-such-pack"), root=root)


def test_loader_names_the_tool_when_only_the_committed_manifests_exist(tmp_path: Path) -> None:
    load = loader()
    root = tmp_path / "assets"
    trees = [f"prompts/{PROMPT_SET}", *(f"context/{name}" for name in PACKS)]
    for tree in trees:
        committed = REPO / "assets" / tree / MANIFEST
        assert committed.is_file(), f"assets/{tree}/{MANIFEST} is not in the repository"
        (root / tree).mkdir(parents=True)
        shutil.copyfile(committed, root / tree / MANIFEST)
    with pytest.raises(ValueError) as caught:
        load({"prompts": PROMPT_SET, "context": list(PACKS)}, root=root)
    assert TOOL_NAME in str(caught.value), f"the error does not name the tool: {caught.value}"


def test_loader_renders_every_generated_fragment_byte_for_byte(extraction, manifests, upstream) -> None:
    load = loader()
    root = extraction.root()
    assets = load({"prompts": PROMPT_SET, "context": list(PACKS)}, root=root)
    entries = manifests.entries(root / "prompts" / PROMPT_SET)
    assert sorted(assets.fragments) == sorted(entry["key"] for entry in entries)
    for entry in entries:
        text = assets.fragments[entry["key"]]
        same = isinstance(text, str) and text.encode("utf-8") == upstream.value_of(entry).encode("utf-8")
        assert same, f"fragment {entry['key']} is not byte for byte the upstream value its key names"
    assert sorted(assets.packs) == sorted(PACKS)
    for name, (dictionary, key) in PACKS.items():
        same = assets.packs[name] == upstream.dictionaries[dictionary][key]
        assert same, f"pack {name} is not byte for byte {dictionary}[{key!r}]"
